/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CallPython */

#ifndef _Included_runscript27
#define _Included_runscript27
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     python.Python 
 * Method:    runscript27
 * Signature: (Ljava/lang/String;)V
 */

JNIEXPORT void JNICALL Java_python_Python_pyinitialize
  (JNIEnv *env, jclass obj);

JNIEXPORT void JNICALL Java_python_Python_pyfinalize
  (JNIEnv *env, jclass obj);

JNIEXPORT void JNICALL Java_python_Python_runscript27
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
